### ISSUE TITLE
Critérios de sucesso na identificação dos objetos no video

### ISSUE THREAD

**Issue by baleiro** [michelpf/fiap-ml-visao-computacional-capstone#1]
Os números de imagens indicados nos criterios de sucesso na etapa de identificação em vídeos indicam o valor exato que deve ser encontrados ou valores mínimos para identificação ? O projeto desenvolvido pode encontrar mais objetos ou é necessário ajustar os parâmetros de threshold para encontrar exatamente os valores indicados nos critérios ?

**Comment by michelpf** [comment]
Não, é apenas uma referência.
Evidências com +/- 20% destes valores eu considero como sucesso também.

No caso das suas evidências ficarem muito abaixo do critério de sucesso, sim, demandará ajustes naqueles valores citados no _notebook_, como o _thresholding_ e o _nms_.
