### ISSUE TITLE
Dúvida sobre a função

### ISSUE THREAD

**Issue by MartaFreitas** [michelpf/fiap-ml-visao-computacional-capstone#11]
Professor, poderia explicar o que deve ser feito e o retorno esperado na função `padronizarROI`  da etapa 4.1 pois não entendi o que as linhas com `img_to_array` e `np.expand_dims` faz.

A nossa implementação ficou dessa forma, mas não tem um return legível.

```
def padronizarROI(imagem):
    # IMPLEMENTAR 1
    novo_tamanho = (200,200)
    imagem_nova_cubica = cv2.resize(imagem, novo_tamanho, interpolation=cv2.INTER_CUBIC)
    imagem = image.img_to_array(imagem_nova_cubica)
    imagem = np.expand_dims(imagem, axis = 0)
     # IMPLEMENTAR 2
    imagem = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
    ret, imagem = cv2.threshold(imagem, 150, 255, cv2.THRESH_BINARY)

    return imagem
```

**Comment by michelpf** [comment]
Olá Marta, as instruções que você cita são transformações necessárias para que a imagem seja lida no padrão que o Keras trabalha.

As imagens no Keras precisam de uma dimensão extra, por isso estas duas transformações.
