### ISSUE TITLE
Dúvida - Colab

### ISSUE THREAD

**Issue by Vicnovais** [michelpf/fiap-ml-visao-computacional-capstone#12]
Boa noite professor!
Nas instruções do notebook há a seguinte instrução:

"Apenas fica vetado o uso de APIs baseadas em cloud."

Utilizamos o Google Colab e o Google Drive para realizar o trabalho em virtude do poder de processamento necessário. Há algum problema?

**Comment by michelpf** [comment]
Olá Victor, pode usar sim.

Apenas é uma ressalva para não usar nenhum _automl_ dos provedores de cloud, como Google AutoML, Azure Computer Vision, etc.
