### ISSUE TITLE
Modelo para identificação de Idade para gênero feminino

### ISSUE THREAD

**Issue by andefuz** [michelpf/fiap-ml-visao-computacional-capstone#13]
Boa noite professor,
Não estou conseguindo atingir o critério de sucesso para a predição da idade para o gênero feminino. Aparentemente estou superestimando as idades e quando verifico idades menor que 45 anos acabo não pegando... atualmente estou com 78 fotos... bem abaixo.
já aumentei o numero de epocas do modelo, mas mesmo assim não consigo melhorar esse item. Estou treinando com todas as imagens (22mil) e também o modelo não melhora para essa parte.
Consegue me ajudar com alguma dica de como posso melhorar o modelo para predizer as idades?

**Comment by michelpf** [comment]
Se você conseguiu atingir os critérios de sucesso nos classificadores, está OK.

Essa referência não é rígida. Ainda que não atinja, para efeitos de correção o processo inteiro, documentado é mais importante. Jornada é mais valiosa do que um resultado fechado.

O que pode ser feito, caso não tenha sido aplicado, é utilizar todas as imagens disponíveis, treinar o modelo com os pesos carregados ao invés de inicialização randômica.
