### ISSUE TITLE
Problemas de memoria para execução do script

### ISSUE THREAD

**Issue by lesomora** [michelpf/fiap-ml-visao-computacional-capstone#15]
Ola Professor, um help....ambos os cases estou passando por problemas com alocação de memoria da GPU. Os pacotes instalados são esses, pode me ajudar: 

absl-py             0.4.1
astor               0.7.1
bleach              3.1.5
certifi             2018.8.24
colorama            0.4.3
cycler              0.10.0
decorator           4.4.2
defusedxml          0.6.0
dlib                19.21.0
entrypoints         0.2.3
gast                0.4.0
grpcio              1.12.1
h5py                2.8.0
ipykernel           4.10.0
ipython             5.8.0
ipython-genutils    0.2.0
ipywidgets          7.4.1
Jinja2              2.11.2
jsonschema          2.6.0
jupyter             1.0.0
jupyter-client      5.3.3
jupyter-console     5.2.0
jupyter-core        4.5.0
Keras               2.2.2
Keras-Applications  1.0.4
Keras-Preprocessing 1.0.2
kiwisolver          1.0.1
Markdown            2.6.11
MarkupSafe          1.0
matplotlib          3.0.0
mistune             0.8.3
mkl-fft             1.0.6
mkl-random          1.0.1
nbconvert           5.5.0
nbformat            5.0.7
notebook            5.6.0
numpy               1.15.2
olefile             0.46
packaging           20.4
pandas              0.23.4
pandocfilters       1.4.2
patsy               0.5.0
pickleshare         0.7.4
Pillow              5.2.0
pip                 20.2.2
prometheus-client   0.8.0
prompt-toolkit      1.0.15
protobuf            3.6.0
Pygments            2.6.1
pyparsing           2.4.7
python-dateutil     2.8.1
pytz                2020.1
pywin32             223
pywinpty            0.5.4
PyYAML              3.13
pyzmq               17.1.2
qtconsole           4.7.5
QtPy                1.9.0
scikit-learn        0.20.0
scipy               1.1.0
seaborn             0.9.0
Send2Trash          1.5.0
setuptools          40.2.0
simplegeneric       0.8.1
six                 1.15.0
statsmodels         0.9.0
TBB                 0.1
tensorboard         1.10.0
tensorflow          1.10.0
termcolor           1.1.0
terminado           0.8.1
testpath            0.4.4
tornado             5.1.1
traitlets           4.3.2
wcwidth             0.2.5
webencodings        0.5.1
Werkzeug            1.0.1
wheel               0.31.1
widgetsnbextension  3.4.1
win-unicode-console 0.5
wincertstore        0.2

**Comment by michelpf** [comment]
Esse projeto requer mais memória mesmo, por isso disponibilizei um Notebook (está no README) no [Collab](https://colab.research.google.com/github/michelpf/fiap-ml-visao-computacional-capstone/blob/master/projeto/object-people-audit-colab.ipynb) para dar uma alternativa a esta condição. Prefira ele ao invés do Notebook original.

Do projeto alternativo (Raio-X) fiz a mesma coisa. No README [dele](https://github.com/michelpf/fiap-ml-visao-computacional-capstone-alternative) você pode verificar ou acessar diretamente [aqui](https://colab.research.google.com/github/michelpf/fiap-ml-visao-computacional-capstone-alternative/blob/master/projeto-final/analise-imagens-medicas-colab.ipynb).

**Comment by lesomora** [comment]
Bom, mesmo rodando esse do Colab e mantendo o maximo de 200 imagens como voce pede la...ele tambem estoura memoria do colab. 

O script em si, não consegui rodar o colab :S 

no caso do meu notebook rs

tenho 48GB de memoria e 8GB de video.....eu deveria consegui rodar esse cara.

Soluções que testei: 

-> usar uma alternativa ao train_test_split ele ta conseguindo de 15 a 20 GB. Sem sucesso, apos treinar a primeira parte coloco valor None nas variaveis X_test, X_train.....

Agora o meu problema esta na alocação da memoria da GPU........ele consome toda a memoria e depois não libera, apos rodar a primeira parte do modelo.

**Comment by michelpf** [comment]
No Colab teste diferentes tamanhos. Eu já consegui rodar com 200, mas se estiver com dificuldade, pode optar por 100, 150. Eu fiz um teste com 100 e rodou normal.

Como são grandes quantidade de dados, a medida que avança você precisa salvar seu modelo off-line (usando o Google Drive) e zerando as variáveis igualando elas a ```None```. Assim a memória vai sendo desalocada.

Diminuir o número de imagens também é uma estratégia válida para execuções locais (com seu próprio computador).

**Comment by rodrwankenobi** [comment]
Também deixando registrado, estou rodando o projeto no colab e estou com muitas dificuldades devido a memória, além de toda vez que a memória estoura, o colab zera todas as variáveis setadas sendo necessário executar tudo de novo. Está dando mais trabalho "rodar o trabalho", do que fazê-lo.

Como sugestão, sugiro que para as próximas turmas seja passada uma atividade onde o foco maior seja nas técnicas de visão computacional, por exemplo, uma tecnica de OCR, redução de ruído e etc, ou trabalhar com um conjunto de dados que não necessite de tanto processamento.

Estou com risco de não entregar o trabalho a tempo, por que não consigo rodar o trabalho no colab, e cada tentativa leva horas e horas.

**Comment by michelpf** [comment]
Por essa razão que temos 2 modelos de projeto. O outro consome menos memória.
Confirma para mim se houve alguma diferença de utilizar GPU ao invés de CPU, por ravor.

**Comment by rodrwankenobi** [comment]
Com gpu o treino do modelo ficou mais rápido, mas não resolveu o problema do estouro de memória

**Comment by rodrwankenobi** [comment]
![image](https://user-images.githubusercontent.com/49798159/163456594-6d1e229f-58d1-4836-a006-e9df55ac7b44.png)

**Comment by michelpf** [comment]
A recomendação é fazer por partes, zerando as variáveis com o None e salvando os arquivos binários dos modelos. Também tem comentários acima sugerindo diminuir o número de imagens. Se mesmo assim você encontrar dificuldades com o ambiente sugiro estudar a outra proposta de projeto.

**Comment by rodrwankenobi** [comment]
Professor poderia considerar aumentar o prazo de entrega em pelo menos 1 dia. Eu comecei a fazer o outro projeto hoje, e vou viajar, não se se conseguirei terminar a tempo.

Obrigado.

**Comment by michelpf** [comment]
Claro, eu amplio, sem problemas! Colocarei mais tempo!

**Comment by rodrwankenobi** [comment]
Muito obrigado pela compreensão e pela ajuda, o problema do raio x está bem mais fácil de executar e mais interessante também. Tivemos uma carga muito intensa de trabalhos esse mês, desculpa pedir de ultima hora

**Comment by michelpf** [comment]
Fica tranquilo!! O importante é o diálogo e como podemos fazer para superar as dificuldades.
Já alterei lá.
