### ISSUE TITLE
Problema ao importar bibliotecas

### ISSUE THREAD

**Issue by rodrwankenobi** [michelpf/fiap-ml-visao-computacional-capstone#18]
Professor, estou com um problema para realizar esta importação
`from tensorflow.keras.layers.core import Dense, Dropout, Activation`

é apresentado o seguinte erro:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12372\2860185359.py in <module>
     15 
     16 from tensorflow.keras.models import Sequential, load_model
---> 17 from tensorflow.keras.layers.core import Dense, Dropout, Activation
     18 import tensorflow.keras
     19 from tensorflow.keras.models import Sequential, Model

ModuleNotFoundError: No module named 'tensorflow.keras.layers.core'
```

Poderia especificar quais versões do tensorflow e keras que você utilizou no template?

Obrigado.

**Comment by rodrwankenobi** [comment]
Dessa forma funcionou:
`from tensorflow.keras.layers import Dense, Dropout, Activation`

Tem algum problema em alterar essa parte?

**Comment by michelpf** [comment]
Vou revisar para a versão mais nova do Keras.

Obrigado pelo feedback.
