### ISSUE TITLE
Dúvida em relação ao Range de Idades

### ISSUE THREAD

**Issue by rodrwankenobi** [michelpf/fiap-ml-visao-computacional-capstone#19]
Professor, abrindo uma nova issue para não misturar os assuntos..

Estou com uma outra dúvida em relação ao range de análise no modelo de idades. No notebook para rodar local, é solicitado para filtrar as idades menores que zero e maiores que 100.

Já no colab, é solicitado para filtrar as menores que 25 e maiores que 60, e quando tem a explicação para a escolha do número de classes, é pedido para colocar 101 (como se as idades fossem de 0 a 100).

Neste caso, qual range devemos considerar?

**Comment by michelpf** [comment]
Tem razão, nesse caso podemos diminuir o número de classes para o limite imposto de 60 (0 a 59), pois cada idade seria como um índice de  classe além de serem esparsos neste conjunto de dados (idade mínima 26 e máxima 59).

As imagens para treinamento e teste devem ser maiores que 25 anos e menores do que 60 anos. Como já filtraríamos por esse range mais amplo não teria necessidade dos ajustes de idades menores do que 0 (inválidas) ou maiores do que 100 (premissa), e também não precisaríamos manter o número de classes em 101.
