### ISSUE TITLE
Problema ao instalar OpenCv

### ISSUE THREAD

**Issue by renato04** [michelpf/fiap-ml-visao-computacional-capstone#2]
Oi! Boa tarde!

Ao tentar instalar o opencv no prompt do anaconda3 está dando o seguinte erro

```
(base) C:\WINDOWS\system32>conda install -c conda-forge opencv
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
```

Poderia me ajudar por favor?

**Comment by michelpf** [comment]
Renato, parece um erro de rede ou algo relacionado a conexão.
Vi alguns comentários deste erro aqui nesta [Issue](https://github.com/conda/conda/issues/6007), tenta ver se a conexão com a internet está OK, se estiver dá uma olhada nas sugestões que citei no link.

Abraço.

**Comment by renato04** [comment]
Muito obrigado!

Vou tentar com a minha conexão de casa depois!

**Comment by renato04** [comment]
Bom dia!

Após instalar e executar o comando que importa os pacotes aparece essa mensagem

![image](https://user-images.githubusercontent.com/5497267/71365277-3f381080-257d-11ea-9b00-9b1e5a86ee82.png)

É normal?

**Comment by michelpf** [comment]
Normal mesmo. É uma mensagem padrão que o Tensorflow gera quando usamos ele pelo Keras.
Pode rodar sem problemas!

Abraço. 😉
