### ISSUE TITLE
É necessário enviar os modelos gerados pelo treinamento das redes neurais ?

### ISSUE THREAD

**Issue by baleiro** [michelpf/fiap-ml-visao-computacional-capstone#3]
Os modelos treinados com extensão h5 das redes neurais devem ser disponibilizados no projeto do GitHub ?
Pergunto isto porque tivemos que habilitar um device LFS para pode subir os arquivos. E, agora, não conseguimos mais fazer a sincronia do repositório por causa do erro: 
"This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."
Precisamos fazer este pagamento ?

**Comment by baleiro** [comment]
Comprei um datapack, são U$5. Obrigado.

**Comment by michelpf** [comment]
Baleiro, acabei não vendo isso.

Não precisa subir não, estes arquivos devem estar inclusive no .gitignore, justamente para subir pois são pesados e honerosos.

Abraço! 😉
