### ISSUE TITLE
Limpeza dos dados

### ISSUE THREAD

**Issue by renato04** [michelpf/fiap-ml-visao-computacional-capstone#4]
Oi!

Em ponto do projeto que diz para limpar os dados de idade menor que zero. O texto diz uma coisa mas código faz outra.

![image](https://user-images.githubusercontent.com/5497267/71368406-a1e1da00-2586-11ea-9d97-c4664b70b2d9.png)

E na validação a mesma coisa.

![image](https://user-images.githubusercontent.com/5497267/71368480-d8b7f000-2586-11ea-8e0b-b5fd7c71e8cc.png)

**Comment by michelpf** [comment]
Renato, de fato houve um erro na visualização. O correto seria ```df[df['age'] < 0``` para visualizar possíveis datas inválidas, em ambos os casos. Eu fiz [este](https://github.com/michelpf/fiap-ml-visao-computacional-capstone/commit/6b7d31beae11fbf279790e0733af4d0a20872de7) commit e [este](https://github.com/michelpf/fiap-ml-visao-computacional-capstone/commit/e7816646d6fda8e9ebf534fb03cc68861443afd8) ajustando isso. 

Obrigado por pontuar!  😉
