### ISSUE TITLE
Estouro de memória RAM

### ISSUE THREAD

**Issue by EduSLima** [michelpf/fiap-ml-visao-computacional-capstone#5]
Boa tarde professor, primeiramente feliz ano novo

Man ... estou simulando o notebook em um i5 com 16 de ram
e já bem no início do processo neste chunk:

> tamanho_imagem = (224, 224) 
faces = []
     for index, row in df.iterrows():
                      image_face = image.load_img("imagens/%s" % ast.literal_eval(row["full_path"])[0], grayscale=False, target_size=tamanho_imagem)
                      image_array = image.img_to_array(image_face).reshape(1, -1)[0]
                      image_array /= 255
                      faces.append(image_array)   

A memória do PC já acaba alguma sugestão ?

**Comment by michelpf** [comment]
Edu, você tem algumas alternativas:

1. Rodar na Cloud, por exemplo AWS, com algum notebook em uma instância com mais memória (Sagemaker, por exemplo).
2. Diminuir o número de imagens (de treinamento) de 5 em 5% até encontrar uma quantidade que rode na sua máquina.
3. Usar um hardware gamer ;)

**Comment by mbracali** [comment]
Tentei sim professor, o problema é que dependendo da quantidade de imagens, o modelo não atingia os critérios mínimos de aceitação do notebook para a generalização do modelo.

No momento eu já consegui resolver o problema dos modelos, treinei e testei os mesmos (idade e genero) com uma série de tunnings que fiz no windows.

Vou tentar resolver sem DLIB então, mas gostaria de acentuar a minha preocupação com a entrega do trabalho, não sei exatamente o custo dos próximos passos do trabalho e também me preocupo em encontrar mais algum ponto que fuja do meu conhecimento.

Obrigado
