### ISSUE TITLE
Problemas com o DLIB

### ISSUE THREAD

**Issue by mbracali** [michelpf/fiap-ml-visao-computacional-capstone#6]
Boa tarde professor.

Estou tendo uma quantidade de problemas relativamente alta para conseguir finalizar o trabalho. No momento não consigo fazer a DLIB funcionar por nada nesse planeta. Estou usando windows 64BIT com PY3.7, e por algum motivo nada consegue fazer essa LIB funcionar.

Professor, também estou preocupado com a data de entrega do trabalho, apesar do notebook estar guiado e nos mostrar exatamente o que fazer e como fazer, os recursos computacionais são exigidos em demasiado. 
Até algumas semanas atras, não havia conseguido uma máquina forte o suficiente para executar o trabalho. Como o senhor havia dito em aula, acredito que esse trabalho esteja realmente bastante acima do que o computador médio consiga executar. Minha máquina só consegue executar o notebook a partir de uma série de tunnings que envolveram mexer na paginação, deletar variáveis e outros truques não muito convencionais, e o pior é que só cheguei na formula, hoje. 
(Meu computador: 16GB de RAM, I7 2682k e GPU R9 390X)
E se rodarmos com menos exemplos o treino/teste dos modelos, os modelos não generalizam tão bem.

Não sei o meu grupo conseguirá entregar o trabalho por uma questão de processamento e algumas variáveis que fogem completamente do nosso conhecimento (DLIB, por exemplo).

Vamos tentar seguir professor, mas se puder dar uma luz vai ser de bastante ajuda.
Obrigado

**Comment by michelpf** [comment]
Olá mbracali,

Vamos lá, o trabalho não exige a instalação do DLib. Você pode fazer a mesma tarefa com o classificador de cascata de Haar.

Sobre o processamento, eu dei a possibilidade para alguns alunos diminuirem a quantidade de imagens de processamento. Já tentou esta possibilidade?

Abraço.

**Comment by ns-bracali** [comment]
Tentei sim professor, o problema é que dependendo da quantidade de imagens, o modelo não atingia os critérios mínimos de aceitação do notebook para a generalização do modelo.

No momento eu já consegui resolver o problema dos modelos, treinei e testei os mesmos (idade e genero) com uma série de tunnings que fiz no windows.

Vou tentar resolver sem DLIB então, mas gostaria de acentuar a minha preocupação com a entrega do trabalho, não sei exatamente o custo dos próximos passos do trabalho e também me preocupo em encontrar mais algum ponto que fuja do meu conhecimento.

Obrigado

**Comment by mbracali** [comment]
Tentei sim professor, o problema é que dependendo da quantidade de imagens, o modelo não atingia os critérios mínimos de aceitação do notebook para a generalização do modelo.

No momento eu já consegui resolver o problema dos modelos, treinei e testei os mesmos (idade e genero) com uma série de tunnings que fiz no windows.

Vou tentar resolver sem DLIB então, mas gostaria de acentuar a minha preocupação com a entrega do trabalho, não sei exatamente o custo dos próximos passos do trabalho e também me preocupo em encontrar mais algum ponto que fuja do meu conhecimento.

Obrigado

**Comment by aantonelloborges** [comment]
Bracali, talvez você tenha que baixar os códigos fontes do DLIB e recompilar com o C++. Eu fiz isso no Ubuntu e deu certo (depois de quase umas semana brigando com a biblioteca).

Abaixo, segue um link semelhante ao que eu realizei mas para o Windows 10: 

https://www.learnopencv.com/install-dlib-on-windows/

Atc,
Angelo

**Comment by michelpf** [comment]
Sobre os critérios, eu posso flexibilizar de acordo com seus comentários a cerca das limitações, detalhando o que você fez para resolver, por exemplo tentando diminuir o batch de treinamento, dentre outras coisas.

Tudo o que for justificado levarei em consideração.

Abraço.

**Comment by mbracali** [comment]
Bom dia professor,

Continuei o trabalho com o haarcascade para continuar com a classificação dos rostos, Infelizmente ele não consegue classificar os dois rostos da foto, apenas um (Brinquei bastante com os parâmetros e mesmo assim não tive sucesso).
E ainda, o próprio notebook pede para usar DLIB, além de mencionar como requisito para inicio do trabalho.
Professor, existe algum tutorial que você recomende para a instalação dessa biblioteca?

Obrigado

**Comment by michelpf** [comment]
Com o classificador de Haar você chegou a alterar o valor de vizinhança próxima para valores menores, como 3?

Instalamos o DLib nas máquinas Windows somente utilizando o ```pip```.

Qual é o seu sistema operacional? 

No Mac você precisa instalar o ```cmake```, para isso use o ```brew```, com este comando ```brew install cmake```.

Se não tem o ```brew```instalado, vá ao site do [Homebrew](https://brew.sh/).

**Comment by mbracali** [comment]
Estou usando Windows, 64BITS, mas quando uso o PIP ele me traz uma série de erros relacionados a CMAKE.

Estou tentando resolver mas é relativamente complicado, acho que vou precisar recompilar as bibliotecas do C.

**Comment by michelpf** [comment]
Antes, disso, apenas me confirme se você alterou esses parâmetros:

```faces = classificador_face.detectMultiScale(imagem_rosto_gray, 1.3, 5)```

O valor 1.3 se trata de redimensionamento de imagens, pode tentar valores como 1.1 e 1.2. Ele faz uma redução de imagem até o tamanho do modelo. Isso melhora a precisão.

O valor 5 é a vizinhança mínima para reconhecer um rosto, se colocar 2 poderá haver muitos falso positivos e se aumentar muito poderá encontrar poucos rostos. Tente achar um meio termo.

Sobre o DLib, estas referências quem sabe podem ajudá-lo:

https://www.learnopencv.com/install-dlib-on-windows/
https://medium.com/beesightsoft/build-dlib-on-windows-534209e8340a
