### ISSUE TITLE
Falta a mais

### ISSUE THREAD

**Issue by LuiYama** [michelpf/fiap-ml-visao-computacional-capstone#7]
Boa noite professor, tudo bem?

Hoje (22/01), abri o aplicativo da FIAP e fui consultar o meu boletim. Tive a surpresa de me deparar que no sistema consta 2 faltas na aula do senhor, inclusive uma na sua última aula de sábado que eu estava presente. Peço por gentileza que o senhor revise essas aulas pois de fato somente faltei uma vez em suas aulas e respondi a todas as chamadas realizadas.
Adicionalmente, para que o senhor lembre, no sábado até brinquei com o senhor por ter feito aulas com o Paulo Sérgio na FEI e fiquei presente na aula até o final.
Abri também um chamado na secretaria e o pessoal deve-lhe procurar sobre esse assunto.

Obrigado,

**Comment by michelpf** [comment]
Estes tipos de casos vamos tratar no e-mail, pois não envolve o projeto final.

Abraço.
