### ISSUE TITLE
Requesitos do Trabalho não ensinados

### ISSUE THREAD

**Issue by aantonelloborges** [michelpf/fiap-ml-visao-computacional-capstone#8]
Professor,

Alguns requisitos do trabalho como o uso do PyTorch e o do Git não foram ensinados em aulas e são exigidos para a entrega.

Creio que boa pare da turma encontrará muita dificuladade nesses dois pontos.

Atc,
Angelo

**Comment by michelpf** [comment]
Olá Angelo,

O projeto cobre o uso do Keras, não do PyTorch.

Aprendemos o Keras na aula 5 e chegamos até executar o Yolo com o Pytorch para demonstrar o uso da classe (```utils.py```) dos criadores (Darknet), nada além disso, por essa razão é que utilizamos o Yolo integrado com o OpenCV e não o Pytorch.

Sobre o uso do Git, desde a primeira aula comentei que a entrega seria por este meio, em especial GitHub, e por tal motivo incentivei a vocês a darem uma lida num tutorial, que segue no material da Aula 0. De todo o modo, para aqueles que tiverem dificuldades, estou a disposição.

Para os alunos que tiverem dificuldade para usar o Git e GitHub pode avisá-los que eles podem me escrever diretamente que lhes ajudarei da melhor forma possível.

Abraço.
