### ISSUE TITLE
critérios de sucesso

### ISSUE THREAD

**Issue by moraisedu10** [michelpf/fiap-ml-visao-computacional-capstone#9]
Professor,

Uma dúvida quanto aos critérios de sucesso do algoritmo: precisamos identificar 180 imagens de homens de qualquer idade ou são 180 imagens de homens acima de 45 anos? Mesmo questionamento para os critérios de identificação de mulher. 
Não ficou totalmente claro no tópico 6 do trabalho. Obrigado

**Comment by michelpf** [comment]
O critério de sucesso é para a identificação do gênero biológico e também da idade associada.
Assim, seriam 180 imagens (não pessoas distintas) de homens com mais de 45 anos e 190 imagens de mulheres com menos de 45.
